name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: VM_HOST
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dockerized-service:latest
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          
    # Authentification GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Déploiement
    - name: Deploy to VM using gcloud
      run: |
        echo "SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }}" > env_file
        echo "AUTH_USERNAME=${{ secrets.AUTH_USERNAME }}" >> env_file
        echo "AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}" >> env_file

        # Copier .env vers la VM
        gcloud compute scp ./env_file ${{ secrets.VM_NAME }}:~/.env \
          --zone=${{ secrets.VM_ZONE }} \
          --project=${{ secrets.GCP_PROJECT_ID }}

        # Exécuter le conteneur sur la VM
        gcloud compute ssh ${{ secrets.VM_NAME }} \
          --zone=${{ secrets.VM_ZONE }} \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --command="
            docker pull ghcr.io/${{ github.repository_owner }}/dockerized-service:latest && \
            docker stop nodejs-app || true && \
            docker rm nodejs-app || true && \
            docker run -d -p 3000:3000 --env-file ~/.env --restart always --name nodejs-app ghcr.io/${{ github.repository_owner }}/dockerized-service:latest
          "
